## Stufe III (Pflicht für alle)

```{r}
#| output: false

task <- tibble::tibble(
    task = "Proteinreich",
    level = 3,
    base_points = 9,
    max_base_points = 12 
) |>
    dplyr::mutate(
        level_points = base_points * level,
        max_level_points = max_base_points * level
    )

tasks <- tasks |> tibble::add_row(task)
```

### `{r} task$task`

Zeige die Reaktionsgleichung für die thermische und metabolische Verbrennung Deiner Aminosäure. Gib die Standardenthalpie für beide Reaktionen an und den respiratorischen Quotienten für die Metabolisierung. Wer eine schwefelhaltige Aminosäure hat bekommt die vierfache Punktzahl, da zusätzlich die Behandlung von Schwefel in der Reaktionsgleichung berücksichtigt werden muss. Wer eine schwefelhaltige Aminosäure oder ähnliche Substanz möchte, sollte sich bei Călin melden.  

#### Vorgehen bei Aminosäuren {.unnumbered}

Bedenke, dass Du auf jeden Fall die Stickstoffatome in der Reaktionsgleichung berücksichtigen musst. Deren Ausscheidung erfolgt über den Harnstoff. Hier ist die Vorgehensweise folgende:

#. Stelle die Reaktionsgleichung für die thermische Verbrennung auf
#. Beziehe die Verbrennungsenthalpie von den gegebenen Quellen
#. Stelle die Reaktionsgleichung für die metabolische Verbrennung auf unter Berücksichtigung der Harnstoffbildung auf
#. Berechne die Standardenthalpie für die metabolische Verbrennung
#. Berechne den respiratorischen Quotienten für die Metabolisierung
#. Lade Deine Ergebnisse in der Aufgabe hoch
#. Trage die Werte in der Exceldatei ein
#. Markiere die Aufgabe als erledigt

#### Vorgehen bei schwefelhaltigen Aminosäuren {.unnumbered}

Falls Du Schwefelatome in Deiner Aminosäure hast, musst Du zusätzlich die Ausscheidung von Schwefel in Form von Schwefelsäure/Sulfat berücksichtigen. Hier empfehle ich folgende Vorgehensweise:

#. Stelle die Reaktionsgleichung für die thermische Verbrennung auf
#. Gewinne aus dieser Reaktionsgleichung die kalorimetrische Verbrennungsgleichung, indem Du die Bildung der Schwefelsäure berücksichtigst.
#. Beziehe die kalorimetrische Verbrennungsenthalpie von den gegebenen Quellen
#. Berechne die thermische Verbrennungsenthalpie unter Berücksichtigung der Bildung von Schwefelsäure
#. Stelle die Reaktionsgleichung für die metabolische Verbrennung auf unter Berücksichtigung der Harnstoffbildung und der Schwefelsäurebildung auf
#. Berechne die Standardenthalpie für die metabolische Verbrennung
#. Berechne den respiratorischen Quotienten für die Metabolisierung
#. Lade Deine Ergebnisse in der Aufgabe hoch
#. Trage die Werte in der Exceldatei ein
#. Markiere die Aufgabe als erledigt    

::: {.fg="purple"}

Du kannst `{r} task$level_points` und maximal `{r} task$max_level_points` Aufgabenpunkte bekommen. Punkte, jeweils mal drei genommen, werden für 

- Die korrekte Reaktionsgleichung der thermischen Verbrennung\*,
- Die beiden Standardenthalpien pro Mol\* und pro Gramm\* für die thermische Verbrennung,
- Die korrekt angepasste Reaktionsgleichung der thermischen Verbrennung von Harnstoff\*; heisst so viele Stickstoffatome in der Reaktionsgleichung wie in der thermischen Verbrennung der Aminosäure vorhanden sind,
- Die zusammengeführte Reaktionsgleichung der metabolischen Verbrennung unter Berücksichtigung der Harnstoffbildung vor dem Kürzen\*,
- Die sich ergebende Reaktionsgleichung der metabolischen Verbrennung nach dem Kürzen\*,
- Die beiden Standardenthalpien pro Mol\* und pro Gramm\* für die metabolische Verbrennung,
- Den respiratorischen Quotienten\*.
- Falls notwendig, das Handling des Schwefels wie in den Lerninhalten gezeigt; mit den Bonuspunkten \*\*\*.

:::

::: {.content-hidden unless-meta="show-rating"}

::: {fg="green-shade-3"}

Punkte, jeweils mal drei genommen, werden für 

- Die korrekte Reaktionsgleichung der thermischen Verbrennung\*,
- Die beiden Standardenthalpien pro Mol\* und pro Gramm\* für die thermische Verbrennung,
- Die korrekt angepasste Reaktionsgleichung der thermischen Verbrennung von Harnstoff\*; heisst so viele Stickstoffatome in der Reaktionsgleichung wie in der thermischen Verbrennung der Aminosäure vorhanden sind,
- Die zusammengeführte Reaktionsgleichung der metabolischen Verbrennung unter Berücksichtigung der Harnstoffbildung vor dem Kürzen\*,
- Die sich ergebende Reaktionsgleichung der metabolischen Verbrennung nach dem Kürzen\*,
- Die beiden Standardenthalpien pro Mol\* und pro Gramm\* für die metabolische Verbrennung,
- Den respiratorischen Quotienten\*.
- Falls notwendig, das Handling des Schwefels wie in den Lerninhalten gezeigt; mit den Bonuspunkten \*\*\*. 

:::

:::